export const REQUEST_ALL_POKEMON = "REQUEST_ALL_POKEMON"
export const RECEIVE_ALL_POKEMON = "RECEIVE_ALL_POKEMON"
export const SELECT_POKEMON = "SELECT_POKEMON"
export const CHECK_POKEMON = "CHECK_POKEMON"
